import test from 'node:test';
import assert from 'node:assert/strict';
import {onRequest as oauth} from '../functions/api/oauth.js';
import {onRequest as callback, classifyKakaoSessionError} from '../functions/api/kakao-callback.js';
import {createFlow, readFlow, kakaoNonce} from '../src/social-auth.js';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test',SUPABASE_SECRET_KEY:'sb_secret_test',KAKAO_REST_API_KEY:'test-rest-api-key',KAKAO_CLIENT_SECRET:'test-client-secret'};
const user={id:'member-id',app_metadata:{provider:'kakao'},user_metadata:{}};
const session={access_token:'supabase-access',refresh_token:'supabase-refresh',expires_in:3600,user};
function req(path,body,cookie=''){return new Request('https://studing.pages.dev'+path,{method:body===undefined?'GET':'POST',headers:{Origin:'https://studing.pages.dev','Content-Type':'application/json',Cookie:cookie},...(body===undefined?{}:{body:JSON.stringify(body)})});}
function mock(t,steps){let calls=0;t.mock.method(globalThis,'fetch',async(url,options)=>{const step=steps[calls++];assert.ok(step,'unexpected fetch');assert.ok(url.includes(step.path),url);step.check?.(options);return new Response(JSON.stringify(step.data??{}),{status:step.status??200});});return()=>assert.equal(calls,steps.length);}
const settings={path:'/settings',data:{external:{google:true,kakao:true}}};
test('Kakao remains unavailable until server app credentials exist',async t=>{mock(t,[settings]);const r=await oauth({env:{...env,KAKAO_CLIENT_SECRET:''},request:req('/api/oauth')});assert.equal((await r.json()).providers.kakao,false);});
test('Kakao authorization requests only openid and never emails or profile scopes',async t=>{mock(t,[settings,{path:'member_auth_limit',data:true}]);const r=await oauth({env,request:req('/api/oauth',{provider:'kakao'})});assert.equal(r.status,200);const data=await r.json(),url=new URL(data.url);assert.equal(url.origin,'https://kauth.kakao.com');assert.equal(url.pathname,'/oauth/authorize');assert.equal(url.searchParams.get('scope'),'openid');assert.equal(url.searchParams.get('redirect_uri'),'https://studing.pages.dev/api/kakao-callback');assert.equal(url.searchParams.get('client_id'),env.KAKAO_REST_API_KEY);const cookie=r.headers.getSetCookie()[0];assert.ok(cookie.startsWith('__Host-member-kakao='));assert.ok(cookie.includes('HttpOnly'));const flow=readFlow(req('/',undefined,cookie),'kakao');assert.equal(url.searchParams.get('state'),flow.nonce);assert.equal(url.searchParams.get('nonce'),await kakaoNonce(flow.verifier));assert.ok(!data.url.includes(flow.verifier));assert.ok(!data.url.includes(env.KAKAO_CLIENT_SECRET));assert.ok(!data.url.includes('account_email'));});
test('Kakao callback rejects missing, incorrect, expired and Google flow cookies before network',async t=>{const done=mock(t,[]);const kakao=await createFlow('kakao'),google=await createFlow();for(const [state,cookie] of [['wrong',kakao.cookie],[kakao.nonce,''],[google.nonce,google.cookie]]){const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+state,undefined,cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_flow_expired');}const value=JSON.parse(decodeURIComponent(kakao.cookie.split(';')[0].split('=')[1]));value.expires=Date.now()-1000;const expired='__Host-member-kakao='+encodeURIComponent(JSON.stringify(value));assert.equal((await callback({env,request:req('/api/kakao-callback?code=test&state='+kakao.nonce,undefined,expired)})).headers.get('Location'),'/?auth=kakao_flow_expired');done();});
test('provider cancellation never exchanges code or sets session cookies',async t=>{const flow=await createFlow('kakao'),done=mock(t,[]);const r=await callback({env,request:req('/api/kakao-callback?error=access_denied&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_cancelled');assert.equal(r.headers.getSetCookie().length,1);done();});
test('server exchanges Kakao code then uses verified ID token for Supabase session',async t=>{const flow=await createFlow('kakao');const done=mock(t,[{path:'kauth.kakao.com/oauth/token',data:{id_token:'kakao-id-token',access_token:'kakao-access'},check:o=>{const b=new URLSearchParams(o.body);assert.equal(b.get('client_secret'),env.KAKAO_CLIENT_SECRET);assert.equal(b.get('redirect_uri'),'https://studing.pages.dev/api/kakao-callback');assert.equal(b.get('code'),'test-code');assert.equal(o.redirect,'manual');assert.equal(typeof o.body,'string');assert.equal(o.headers.Accept,'application/json');}},{path:'grant_type=id_token',data:session,check:o=>{const b=JSON.parse(o.body);assert.deepEqual(b,{provider:'kakao',id_token:'kakao-id-token',access_token:'kakao-access',nonce:flow.verifier});}},{path:'/auth/v1/user',data:user}]);const r=await callback({env,request:req('/api/kakao-callback?code=test-code&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.status,303);assert.equal(r.headers.get('Location'),'/?auth=social');assert.equal(r.headers.getSetCookie().length,3);assert.equal(r.headers.get('Referrer-Policy'),'no-referrer');assert.ok(!r.headers.get('Location').includes('token'));done();});
test('OIDC disabled returns safe feedback without Supabase token exchange',async t=>{const flow=await createFlow('kakao');const done=mock(t,[{path:'kauth.kakao.com/oauth/token',data:{access_token:'kakao-access'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_oidc_required');assert.equal(r.headers.getSetCookie().length,1);done();});
test('invalid ID tokens rejected by Supabase never create login cookies',async t=>{const flow=await createFlow('kakao');const done=mock(t,[{path:'kauth.kakao.com/oauth/token',data:{id_token:'bad-token',access_token:'kakao-access'}},{path:'grant_type=id_token',status:400,data:{error:'invalid_nonce'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_nonce_failed');assert.equal(r.headers.getSetCookie().length,1);done();});
test('unverified Supabase user response cannot create session cookies',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',data:{id_token:'token',access_token:'kakao-access'}},{path:'grant_type=id_token',data:session},{path:'/auth/v1/user',status:401}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_session_failed');assert.equal(r.headers.getSetCookie().length,1);});
test('safe classification distinguishes email, app and member setup without leaking upstream errors',()=>{assert.equal(classifyKakaoSessionError({error_code:'email_not_found'}),'kakao_email_required');assert.equal(classifyKakaoSessionError({msg:'Unacceptable audience in id_token: SECRET-VALUE'}),'kakao_app_mismatch');assert.equal(classifyKakaoSessionError({code:'provider_disabled'}),'kakao_provider_disabled');assert.equal(classifyKakaoSessionError({message:'Database error saving new user'}),'kakao_member_setup');assert.equal(classifyKakaoSessionError({message:'unknown SECRET-VALUE'}),'kakao_supabase_failed');});
test('email required failure returns a safe category and no session cookies',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',data:{id_token:'token',access_token:'kakao-access'}},{path:'grant_type=id_token',status:400,data:{code:'email_not_found',message:'Email address is required SECRET-VALUE'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_email_required');assert.equal(r.headers.getSetCookie().length,1);assert.ok(!r.headers.get('Location').includes('SECRET-VALUE'));});
test('wrong client secret is distinguished without exposing it',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',status:401,data:{error_code:'KOE010',error_description:env.KAKAO_CLIENT_SECRET}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_secret_invalid');assert.ok(!r.headers.get('Location').includes(env.KAKAO_CLIENT_SECRET));});
test('expired authorization code is distinguished from app configuration failures',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',status:400,data:{error_code:'KOE320',error_description:'authorization code not found SECRET-CODE'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_code_expired');assert.equal(r.headers.getSetCookie().length,1);assert.ok(!r.headers.get('Location').includes('SECRET-CODE'));});
test('redirect mismatch returns a specific safe reason',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',status:400,data:{error_code:'KOE303'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_redirect_mismatch');});
test('unknown provider error exposes only valid public code, never raw description',async t=>{const flow=await createFlow('kakao');mock(t,[{path:'kauth.kakao.com/oauth/token',status:400,data:{error_code:'KOE999',error_description:'SECRET-DATA'}}]);const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_token_failed&detail=KOE999');});
test('transport exceptions cannot be mistaken for credential errors or leak exception text',async t=>{t.mock.method(globalThis,'fetch',async()=>{throw new TypeError('fetch failed SECRET-TOKEN');});const flow=await createFlow('kakao');const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_connection_failed');assert.equal(r.headers.getSetCookie().length,1);assert.ok(!r.headers.get('Location').includes('SECRET-TOKEN'));});
test('network timeouts are distinguished without retrying one-time authorization codes',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw new DOMException('time limit','TimeoutError');});const flow=await createFlow('kakao');const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_connection_timeout');assert.equal(calls,1);});
test('unexpected token endpoint redirects are not followed with app credentials',async t=>{t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://untrusted.example'}});});const flow=await createFlow('kakao');const r=await callback({env,request:req('/api/kakao-callback?code=test&state='+flow.nonce,undefined,flow.cookie)});assert.equal(r.headers.get('Location'),'/?auth=kakao_token_failed&detail=HTTP302');assert.equal(r.headers.getSetCookie().length,1);});
